import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React, { ReactNode } from 'react';

const Navbar = () => {
  return (
    <header className="bg-gray-900 text-white w-full py-4 absolute top-0">
      <div className="mx-auto flex items-center justify-end h-5 px-10">
        <nav>
          <ul className="flex gap-10">
            <li><a href="/" className="hover:text-blue-500">Home</a></li>
            <li><a href="#projects" className="hover:text-blue-500">Projects</a></li>
            <li><a href="#skills" className="hover:text-blue-500">Skills</a></li>
          </ul>
        </nav>
      </div>
    </header>
  );
};

const Footer = () => {
  return (
    <footer className="bg-gray-900 text-white py-4 w-full">
      <div className="justify-end text-center p-1">
        <p>&copy; {new Date().getFullYear()} Mukund Iyer. All rights reserved.</p>
      </div>
    </footer>
  );
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        {/* Your head section content */}
      </head>
      <body className={`flex flex-col min-h-screen ${inter.className}`}>
        <Navbar />
        <main className="flex-grow">
          <div className="container mx-auto flex flex-col p-4">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
